[project]
entry = "main.sw"
license = "Apache-2.0"
name = "pyth_mock"

[dependencies]
pyth_interface = { git = "https://github.com/pyth-network/pyth-crosschain", rev = "7de4ce3ec8defd97641c1d25302abe117bf5092b" }
